import Foundation

// Generated by tools/dev/generate_nt212x_parameter_constants.py
// Source: core/src/protocol/module/nt212x_parameter_catalog.inc
public enum Nt212xParameterCatalog {
    public static var all: [Nt212xParameterDefinition] {
        RuntimeParameterCatalogFallback.nt212xDefinitions
    }

    public static func findByID(_ parameterID: UInt16) -> Nt212xParameterDefinition? {
        all.first { $0.parameterID == parameterID }
    }
}
