import Foundation

// Generated by tools/dev/generate_nt212x_parameter_constants.py
// Source: core/src/protocol/module/nt212x_parameter_catalog.inc
public enum Nt212xParameterAliases {
    public static let code39Enable: UInt16 = Nt212xParameters.param00
    public static let upcAEnable: UInt16 = Nt212xParameters.param01
    public static let upcEEnable: UInt16 = Nt212xParameters.param02
    public static let ean13Enable: UInt16 = Nt212xParameters.param03
    public static let ean8Enable: UInt16 = Nt212xParameters.param04
    public static let interleaved2Of5Enable: UInt16 = Nt212xParameters.param06
    public static let codabarEnable: UInt16 = Nt212xParameters.param07
    public static let code128Enable: UInt16 = Nt212xParameters.param08
    public static let code93Enable: UInt16 = Nt212xParameters.param09
    public static let code11Enable: UInt16 = Nt212xParameters.param0A
    public static let msiEnable: UInt16 = Nt212xParameters.param0B
    public static let gs1128Enable: UInt16 = Nt212xParameters.param0E
    public static let pdf417Enable: UInt16 = Nt212xParameters.param0F
    public static let code39FullAsciiEnable: UInt16 = Nt212xParameters.param11
    public static let code39Length1: UInt16 = Nt212xParameters.param12
    public static let code39Length2: UInt16 = Nt212xParameters.param13
    public static let discrete2Of5Length1: UInt16 = Nt212xParameters.param14
    public static let discrete2Of5Length2: UInt16 = Nt212xParameters.param15
    public static let interleaved2Of5Length1: UInt16 = Nt212xParameters.param16
    public static let interleaved2Of5Length2: UInt16 = Nt212xParameters.param17
    public static let codabarLength1: UInt16 = Nt212xParameters.param18
    public static let codabarLength2: UInt16 = Nt212xParameters.param19
    public static let code93Length1: UInt16 = Nt212xParameters.param1A
    public static let code93Length2: UInt16 = Nt212xParameters.param1B
    public static let code11Length1: UInt16 = Nt212xParameters.param1C
    public static let code11Length2: UInt16 = Nt212xParameters.param1D
    public static let msiLength1: UInt16 = Nt212xParameters.param1E
    public static let msiLength2: UInt16 = Nt212xParameters.param1F
    public static let upcAPreamble: UInt16 = Nt212xParameters.param22
    public static let upcEPreamble: UInt16 = Nt212xParameters.param23
    public static let convertUpcEToUpcA: UInt16 = Nt212xParameters.param25
    public static let ean8ZeroExtend: UInt16 = Nt212xParameters.param27
    public static let transmitUpcACheckDigit: UInt16 = Nt212xParameters.param28
    public static let transmitUpcECheckDigit: UInt16 = Nt212xParameters.param29
    public static let code39TransmitCheckDigit: UInt16 = Nt212xParameters.param2B
    public static let codeIdCharacter: UInt16 = Nt212xParameters.param2D
    public static let transmitMsiCheckCode: UInt16 = Nt212xParameters.param2E
    public static let transmitCode11CheckDigit: UInt16 = Nt212xParameters.param2F
    public static let code39CheckDigitVerify: UInt16 = Nt212xParameters.param30
    public static let msiCheckDigitCount: UInt16 = Nt212xParameters.param32
    public static let msiAlgorithm: UInt16 = Nt212xParameters.param33
    public static let code11CheckCodeVerify: UInt16 = Nt212xParameters.param34
    public static let notisEdit: UInt16 = Nt212xParameters.param37
    public static let goodReadBeep: UInt16 = Nt212xParameters.param38
    public static let linearCodeSecurityLevel: UInt16 = Nt212xParameters.param4E
    public static let booklandEanIsbnEnable: UInt16 = Nt212xParameters.param53
    public static let isbt128Enable: UInt16 = Nt212xParameters.param54
    public static let convertCode39ToCode32: UInt16 = Nt212xParameters.param56
    public static let noReadMessage: UInt16 = Nt212xParameters.param5E
    public static let suffix1Value: UInt16 = Nt212xParameters.param68
    public static let prefixValue: UInt16 = Nt212xParameters.param69
    public static let suffix2Value: UInt16 = Nt212xParameters.param6A
    public static let scanDuration: UInt16 = Nt212xParameters.param88
    public static let beeperVolume: UInt16 = Nt212xParameters.param8C
    public static let baudRate: UInt16 = Nt212xParameters.param9C
    public static let stopBits: UInt16 = Nt212xParameters.param9D
    public static let parity: UInt16 = Nt212xParameters.param9E
    public static let softwareHandshake: UInt16 = Nt212xParameters.param9F
    public static let dataBits: UInt16 = Nt212xParameters.paramA0
    public static let code32Prefix: UInt16 = Nt212xParameters.paramE7
    public static let scanConfigBarcode: UInt16 = Nt212xParameters.paramEC
    public static let decodePacketFormat: UInt16 = Nt212xParameters.paramEE
    public static let dataMatrixEnable: UInt16 = Nt212xParameters.paramF024
    public static let qrCodeEnable: UInt16 = Nt212xParameters.paramF025
    public static let maxiCodeEnable: UInt16 = Nt212xParameters.paramF026
    public static let aztecCodeEnable: UInt16 = Nt212xParameters.paramF028
    public static let hanXinCodeEnable: UInt16 = Nt212xParameters.paramF02f
    public static let gs1DataBarRssEnable: UInt16 = Nt212xParameters.paramF052
    public static let transmitSetupCode: UInt16 = Nt212xParameters.paramF171
    public static let sensitivityLevel: UInt16 = Nt212xParameters.paramF204
    public static let terminator: UInt16 = Nt212xParameters.paramF205
    public static let outputCharset: UInt16 = Nt212xParameters.paramF206
    public static let vatInvoiceAutoOutput: UInt16 = Nt212xParameters.paramF208
    public static let indicatorControl: UInt16 = Nt212xParameters.paramF20a
    public static let goodReadLed: UInt16 = Nt212xParameters.paramF20b
    public static let muteMode: UInt16 = Nt212xParameters.paramF20c
    public static let usbType: UInt16 = Nt212xParameters.paramF20f
    public static let linearCodeEnable: UInt16 = Nt212xParameters.paramF211
    public static let upcE1Enable: UInt16 = Nt212xParameters.paramF215
    public static let ean13CheckCharacter: UInt16 = Nt212xParameters.paramF216
    public static let compositeEnable: UInt16 = Nt212xParameters.paramF217
    public static let code32CheckCodeVerify: UInt16 = Nt212xParameters.paramF219
    public static let transmitCode32CheckDigit: UInt16 = Nt212xParameters.paramF21a
    public static let matrix25Enable: UInt16 = Nt212xParameters.paramF220
    public static let matrix25CheckDigitVerify: UInt16 = Nt212xParameters.paramF221
    public static let transmitMatrix25CheckCharacter: UInt16 = Nt212xParameters.paramF222
    public static let rssAiCharacter: UInt16 = Nt212xParameters.paramF226
    public static let code39TransmitStartStopCharacter: UInt16 = Nt212xParameters.paramF230
    public static let code128CheckCharacter: UInt16 = Nt212xParameters.paramF235
    public static let gs1128CheckCharacter: UInt16 = Nt212xParameters.paramF236
    public static let ean82Digit: UInt16 = Nt212xParameters.paramF237
    public static let ean85Digit: UInt16 = Nt212xParameters.paramF238
    public static let ean8AddonRequired: UInt16 = Nt212xParameters.paramF239
    public static let ean132Digit: UInt16 = Nt212xParameters.paramF23a
    public static let ean135Digit: UInt16 = Nt212xParameters.paramF23b
    public static let ean13AddonRequired: UInt16 = Nt212xParameters.paramF23c
    public static let upcE2Digit: UInt16 = Nt212xParameters.paramF23d
    public static let upcE5Digit: UInt16 = Nt212xParameters.paramF23e
    public static let upcEAddonRequired: UInt16 = Nt212xParameters.paramF23f
    public static let upcA2Digit: UInt16 = Nt212xParameters.paramF240
    public static let upcA5Digit: UInt16 = Nt212xParameters.paramF241
    public static let upcAAddonRequired: UInt16 = Nt212xParameters.paramF242
    public static let discrete2Of5: UInt16 = Nt212xParameters.paramF248
    public static let discrete2Of5CheckCharacter: UInt16 = Nt212xParameters.paramF249
    public static let codabarChecksum: UInt16 = Nt212xParameters.paramF24c
    public static let codabarCheckCharacter: UInt16 = Nt212xParameters.paramF24d
    public static let twoDimensionalCodeEnable: UInt16 = Nt212xParameters.paramF250
    public static let pdf417InverseDecodeMode: UInt16 = Nt212xParameters.paramF261
    public static let qrCodeEciControl: UInt16 = Nt212xParameters.paramF266
    public static let qrCodeInverseDecodeMode: UInt16 = Nt212xParameters.paramF267
    public static let dataMatrixInverseDecodeMode: UInt16 = Nt212xParameters.paramF26b
    public static let dataMatrixEciControl: UInt16 = Nt212xParameters.paramF26c
    public static let hanXinInverseDecodeMode: UInt16 = Nt212xParameters.paramF271
    public static let ean8CheckDigit: UInt16 = Nt212xParameters.paramF280
    public static let allSymbologyEnable: UInt16 = Nt212xParameters.paramF290
    public static let linearInverseBarcodeDecode: UInt16 = Nt212xParameters.paramF291
    public static let letterCaseTransform: UInt16 = Nt212xParameters.paramF2A1
    public static let powerOnEvent: UInt16 = Nt212xParameters.paramF2A2
    public static let triggerDecodeEvent: UInt16 = Nt212xParameters.paramF2A3
    public static let wiegandProtocol: UInt16 = Nt212xParameters.paramF2A4
    public static let wiegand26OutputMode: UInt16 = Nt212xParameters.paramF2A5
    public static let setupCodePasswordMode: UInt16 = Nt212xParameters.paramF2A7
    public static let disablePassiveTriggerScan: UInt16 = Nt212xParameters.paramF2A8
    public static let invoiceType: UInt16 = Nt212xParameters.paramF2Aa
    public static let inputCharset: UInt16 = Nt212xParameters.paramF2Ab
    public static let keyboardOutputIntervalPreset: UInt16 = Nt212xParameters.paramF2B2
    public static let keyboardType: UInt16 = Nt212xParameters.paramF2B4
    public static let stxAndEtxMode: UInt16 = Nt212xParameters.paramF2B7
    public static let keyboardStateControl: UInt16 = Nt212xParameters.paramF2B9
    public static let duplicateDelayPreset: UInt16 = Nt212xParameters.paramF2C9
    public static let decodeIndicatorControl: UInt16 = Nt212xParameters.paramF2Cb
    public static let heartbeatMode: UInt16 = Nt212xParameters.paramF2Cd
    public static let singleScanDuration: UInt16 = Nt212xParameters.paramF2Cf
    public static let beeperType: UInt16 = Nt212xParameters.paramF2D8
    public static let insertCustomDataEnable: UInt16 = Nt212xParameters.paramF2De
    public static let urlFilter: UInt16 = Nt212xParameters.paramF2Ea
    public static let defaultProfile: UInt16 = Nt212xParameters.paramF2Ff
    public static let customSensitivity: UInt16 = Nt212xParameters.paramF301
    public static let keyboardCharacterInterval: UInt16 = Nt212xParameters.paramF304
    public static let enterSetupCodePassword: UInt16 = Nt212xParameters.paramF305
    public static let multiPrefix: UInt16 = Nt212xParameters.paramF310
    public static let multiSuffix: UInt16 = Nt212xParameters.paramF311
    public static let prefixBySymbology: UInt16 = Nt212xParameters.paramF312
    public static let suffixBySymbology: UInt16 = Nt212xParameters.paramF313
    public static let wiegandOutputInterval: UInt16 = Nt212xParameters.paramF316
    public static let insertDataPosition: UInt16 = Nt212xParameters.paramF317
    public static let insertDataValue: UInt16 = Nt212xParameters.paramF31a
    public static let hiddenDataValue: UInt16 = Nt212xParameters.paramF32a
    public static let code128Length1: UInt16 = Nt212xParameters.paramF504
    public static let code128Length2: UInt16 = Nt212xParameters.paramF505
    public static let gs1128Length1: UInt16 = Nt212xParameters.paramF506
    public static let gs1128Length2: UInt16 = Nt212xParameters.paramF507
    public static let nEC25Length1: UInt16 = Nt212xParameters.paramF508
    public static let nEC25Length2: UInt16 = Nt212xParameters.paramF509
    public static let keyboardLayout: UInt16 = Nt212xParameters.paramF601
    public static let suffixAltCombination: UInt16 = Nt212xParameters.paramF62b
    public static let suffixCtrlCombination: UInt16 = Nt212xParameters.paramF62c
    public static let suffixShiftCombination: UInt16 = Nt212xParameters.paramF62d
    public static let rs485BufferDecodeData: UInt16 = Nt212xParameters.paramF62e
    public static let rs485NetworkEnable: UInt16 = Nt212xParameters.paramF633
    public static let rs485DecodeDataFormat: UInt16 = Nt212xParameters.paramF634
    public static let rs485HeartbeatEnable: UInt16 = Nt212xParameters.paramF635
    public static let continuousScan: UInt16 = Nt212xParameters.paramF639
    public static let qrCodeUtf8Bom: UInt16 = Nt212xParameters.paramF63a
    public static let hexOutputOrModbusRtuMode: UInt16 = Nt212xParameters.paramF641
    public static let hexOutputSeparator: UInt16 = Nt212xParameters.paramF642
    public static let suffixAndTerminatorIgnoreAsciiCtrlMode: UInt16 = Nt212xParameters.paramF649
    public static let hideCustomDataEnable: UInt16 = Nt212xParameters.paramF668
    public static let hiddenDataReadOrClear: UInt16 = Nt212xParameters.paramF669
    public static let suppressDuplicateInDecodeCycle: UInt16 = Nt212xParameters.paramF66b
    public static let rs485DeviceAddressQuickSet: UInt16 = Nt212xParameters.paramF811
    public static let quickMultiPrefix: UInt16 = Nt212xParameters.paramF814
    public static let quickMultiSuffix: UInt16 = Nt212xParameters.paramF815
    public static let exitCustomDataSetup: UInt16 = Nt212xParameters.paramFFF6

    public static func getLabel(parameterID: UInt16) -> String? {
        switch parameterID {
        case code39Enable: return "Code39Enable"
        case upcAEnable: return "UpcAEnable"
        case upcEEnable: return "UpcEEnable"
        case ean13Enable: return "Ean13Enable"
        case ean8Enable: return "Ean8Enable"
        case interleaved2Of5Enable: return "Interleaved2Of5Enable"
        case codabarEnable: return "CodabarEnable"
        case code128Enable: return "Code128Enable"
        case code93Enable: return "Code93Enable"
        case code11Enable: return "Code11Enable"
        case msiEnable: return "MsiEnable"
        case gs1128Enable: return "Gs1128Enable"
        case pdf417Enable: return "Pdf417Enable"
        case code39FullAsciiEnable: return "Code39FullAsciiEnable"
        case code39Length1: return "Code39Length1"
        case code39Length2: return "Code39Length2"
        case discrete2Of5Length1: return "Discrete2Of5Length1"
        case discrete2Of5Length2: return "Discrete2Of5Length2"
        case interleaved2Of5Length1: return "Interleaved2Of5Length1"
        case interleaved2Of5Length2: return "Interleaved2Of5Length2"
        case codabarLength1: return "CodabarLength1"
        case codabarLength2: return "CodabarLength2"
        case code93Length1: return "Code93Length1"
        case code93Length2: return "Code93Length2"
        case code11Length1: return "Code11Length1"
        case code11Length2: return "Code11Length2"
        case msiLength1: return "MsiLength1"
        case msiLength2: return "MsiLength2"
        case upcAPreamble: return "UpcAPreamble"
        case upcEPreamble: return "UpcEPreamble"
        case convertUpcEToUpcA: return "ConvertUpcEToUpcA"
        case ean8ZeroExtend: return "Ean8ZeroExtend"
        case transmitUpcACheckDigit: return "TransmitUpcACheckDigit"
        case transmitUpcECheckDigit: return "TransmitUpcECheckDigit"
        case code39TransmitCheckDigit: return "Code39TransmitCheckDigit"
        case codeIdCharacter: return "CodeIdCharacter"
        case transmitMsiCheckCode: return "TransmitMsiCheckCode"
        case transmitCode11CheckDigit: return "TransmitCode11CheckDigit"
        case code39CheckDigitVerify: return "Code39CheckDigitVerify"
        case msiCheckDigitCount: return "MsiCheckDigitCount"
        case msiAlgorithm: return "MsiAlgorithm"
        case code11CheckCodeVerify: return "Code11CheckCodeVerify"
        case notisEdit: return "NotisEdit"
        case goodReadBeep: return "GoodReadBeep"
        case linearCodeSecurityLevel: return "LinearCodeSecurityLevel"
        case booklandEanIsbnEnable: return "BooklandEanIsbnEnable"
        case isbt128Enable: return "Isbt128Enable"
        case convertCode39ToCode32: return "ConvertCode39ToCode32"
        case noReadMessage: return "NoReadMessage"
        case suffix1Value: return "Suffix1Value"
        case prefixValue: return "PrefixValue"
        case suffix2Value: return "Suffix2Value"
        case scanDuration: return "ScanDuration"
        case beeperVolume: return "BeeperVolume"
        case baudRate: return "BaudRate"
        case stopBits: return "StopBits"
        case parity: return "Parity"
        case softwareHandshake: return "SoftwareHandshake"
        case dataBits: return "DataBits"
        case code32Prefix: return "Code32Prefix"
        case scanConfigBarcode: return "ScanConfigBarcode"
        case decodePacketFormat: return "DecodePacketFormat"
        case dataMatrixEnable: return "DataMatrixEnable"
        case qrCodeEnable: return "QrCodeEnable"
        case maxiCodeEnable: return "MaxiCodeEnable"
        case aztecCodeEnable: return "AztecCodeEnable"
        case hanXinCodeEnable: return "HanXinCodeEnable"
        case gs1DataBarRssEnable: return "Gs1DataBarRssEnable"
        case transmitSetupCode: return "TransmitSetupCode"
        case sensitivityLevel: return "SensitivityLevel"
        case terminator: return "Terminator"
        case outputCharset: return "OutputCharset"
        case vatInvoiceAutoOutput: return "VatInvoiceAutoOutput"
        case indicatorControl: return "IndicatorControl"
        case goodReadLed: return "GoodReadLed"
        case muteMode: return "MuteMode"
        case usbType: return "UsbType"
        case linearCodeEnable: return "LinearCodeEnable"
        case upcE1Enable: return "UpcE1Enable"
        case ean13CheckCharacter: return "Ean13CheckCharacter"
        case compositeEnable: return "CompositeEnable"
        case code32CheckCodeVerify: return "Code32CheckCodeVerify"
        case transmitCode32CheckDigit: return "TransmitCode32CheckDigit"
        case matrix25Enable: return "Matrix25Enable"
        case matrix25CheckDigitVerify: return "Matrix25CheckDigitVerify"
        case transmitMatrix25CheckCharacter: return "TransmitMatrix25CheckCharacter"
        case rssAiCharacter: return "RssAiCharacter"
        case code39TransmitStartStopCharacter: return "Code39TransmitStartStopCharacter"
        case code128CheckCharacter: return "Code128CheckCharacter"
        case gs1128CheckCharacter: return "Gs1128CheckCharacter"
        case ean82Digit: return "Ean82Digit"
        case ean85Digit: return "Ean85Digit"
        case ean8AddonRequired: return "Ean8AddonRequired"
        case ean132Digit: return "Ean132Digit"
        case ean135Digit: return "Ean135Digit"
        case ean13AddonRequired: return "Ean13AddonRequired"
        case upcE2Digit: return "UpcE2Digit"
        case upcE5Digit: return "UpcE5Digit"
        case upcEAddonRequired: return "UpcEAddonRequired"
        case upcA2Digit: return "UpcA2Digit"
        case upcA5Digit: return "UpcA5Digit"
        case upcAAddonRequired: return "UpcAAddonRequired"
        case discrete2Of5: return "Discrete2Of5"
        case discrete2Of5CheckCharacter: return "Discrete2Of5CheckCharacter"
        case codabarChecksum: return "CodabarChecksum"
        case codabarCheckCharacter: return "CodabarCheckCharacter"
        case twoDimensionalCodeEnable: return "TwoDimensionalCodeEnable"
        case pdf417InverseDecodeMode: return "Pdf417InverseDecodeMode"
        case qrCodeEciControl: return "QrCodeEciControl"
        case qrCodeInverseDecodeMode: return "QrCodeInverseDecodeMode"
        case dataMatrixInverseDecodeMode: return "DataMatrixInverseDecodeMode"
        case dataMatrixEciControl: return "DataMatrixEciControl"
        case hanXinInverseDecodeMode: return "HanXinInverseDecodeMode"
        case ean8CheckDigit: return "Ean8CheckDigit"
        case allSymbologyEnable: return "AllSymbologyEnable"
        case linearInverseBarcodeDecode: return "LinearInverseBarcodeDecode"
        case letterCaseTransform: return "LetterCaseTransform"
        case powerOnEvent: return "PowerOnEvent"
        case triggerDecodeEvent: return "TriggerDecodeEvent"
        case wiegandProtocol: return "WiegandProtocol"
        case wiegand26OutputMode: return "Wiegand26OutputMode"
        case setupCodePasswordMode: return "SetupCodePasswordMode"
        case disablePassiveTriggerScan: return "DisablePassiveTriggerScan"
        case invoiceType: return "InvoiceType"
        case inputCharset: return "InputCharset"
        case keyboardOutputIntervalPreset: return "KeyboardOutputIntervalPreset"
        case keyboardType: return "KeyboardType"
        case stxAndEtxMode: return "StxAndEtxMode"
        case keyboardStateControl: return "KeyboardStateControl"
        case duplicateDelayPreset: return "DuplicateDelayPreset"
        case decodeIndicatorControl: return "DecodeIndicatorControl"
        case heartbeatMode: return "HeartbeatMode"
        case singleScanDuration: return "SingleScanDuration"
        case beeperType: return "BeeperType"
        case insertCustomDataEnable: return "InsertCustomDataEnable"
        case urlFilter: return "UrlFilter"
        case defaultProfile: return "DefaultProfile"
        case customSensitivity: return "CustomSensitivity"
        case keyboardCharacterInterval: return "KeyboardCharacterInterval"
        case enterSetupCodePassword: return "EnterSetupCodePassword"
        case multiPrefix: return "MultiPrefix"
        case multiSuffix: return "MultiSuffix"
        case prefixBySymbology: return "PrefixBySymbology"
        case suffixBySymbology: return "SuffixBySymbology"
        case wiegandOutputInterval: return "WiegandOutputInterval"
        case insertDataPosition: return "InsertDataPosition"
        case insertDataValue: return "InsertDataValue"
        case hiddenDataValue: return "HiddenDataValue"
        case code128Length1: return "Code128Length1"
        case code128Length2: return "Code128Length2"
        case gs1128Length1: return "Gs1128Length1"
        case gs1128Length2: return "Gs1128Length2"
        case nEC25Length1: return "NEC25Length1"
        case nEC25Length2: return "NEC25Length2"
        case keyboardLayout: return "KeyboardLayout"
        case suffixAltCombination: return "SuffixAltCombination"
        case suffixCtrlCombination: return "SuffixCtrlCombination"
        case suffixShiftCombination: return "SuffixShiftCombination"
        case rs485BufferDecodeData: return "Rs485BufferDecodeData"
        case rs485NetworkEnable: return "Rs485NetworkEnable"
        case rs485DecodeDataFormat: return "Rs485DecodeDataFormat"
        case rs485HeartbeatEnable: return "Rs485HeartbeatEnable"
        case continuousScan: return "ContinuousScan"
        case qrCodeUtf8Bom: return "QrCodeUtf8Bom"
        case hexOutputOrModbusRtuMode: return "HexOutputOrModbusRtuMode"
        case hexOutputSeparator: return "HexOutputSeparator"
        case suffixAndTerminatorIgnoreAsciiCtrlMode: return "SuffixAndTerminatorIgnoreAsciiCtrlMode"
        case hideCustomDataEnable: return "HideCustomDataEnable"
        case hiddenDataReadOrClear: return "HiddenDataReadOrClear"
        case suppressDuplicateInDecodeCycle: return "SuppressDuplicateInDecodeCycle"
        case rs485DeviceAddressQuickSet: return "Rs485DeviceAddressQuickSet"
        case quickMultiPrefix: return "QuickMultiPrefix"
        case quickMultiSuffix: return "QuickMultiSuffix"
        case exitCustomDataSetup: return "ExitCustomDataSetup"
        default: return nil
        }
    }
}
