import Foundation

// Generated by tools/dev/generate_nt280h_parameter_constants.py
// Source: core/src/protocol/module/nt280h_parameter_catalog.inc
public enum Nt280hParameters {
    public static let queryAction: UInt16 = 0x0E0D
    public static let ackResponseControl: UInt16 = 0xA000
    public static let scanControl: UInt16 = 0xA001
    public static let saveSettings: UInt16 = 0xA008
    public static let factoryDefaults: UInt16 = 0xA101
    public static let scanMode: UInt16 = 0xA102
    public static let aimer: UInt16 = 0xA103
    public static let illuminationMode: UInt16 = 0xA104
    public static let beeper: UInt16 = 0xA105
    public static let decodeTimeout: UInt16 = 0xA106
    public static let sleepTimeout: UInt16 = 0xA107
    public static let duplicateReadDelay: UInt16 = 0xA108
    public static let illuminationIntensity: UInt16 = 0xA109
    public static let autoSenseSensitivity: UInt16 = 0xA10A
    public static let decodeDataVerification: UInt16 = 0xA10B
    public static let decodeMessage: UInt16 = 0xA201
    public static let symbologyIdentifier: UInt16 = 0xA202
    public static let terminator: UInt16 = 0xA203
    public static let allSymbologyEnable: UInt16 = 0xB001
    public static let upcEanAddonEnable: UInt16 = 0xB002
    public static let upcAEnable: UInt16 = 0xB101
    public static let upcATransmitLeadingDigit: UInt16 = 0xB102
    public static let upcACheckDigit: UInt16 = 0xB103
    public static let upcAConvertToEan13: UInt16 = 0xB104
    public static let upcEEnable: UInt16 = 0xB201
    public static let ean8Enable: UInt16 = 0xB301
    public static let ean13Enable: UInt16 = 0xB401
    public static let ean13ConvertToIsbn: UInt16 = 0xB403
    public static let ean13ConvertToIssn: UInt16 = 0xB404
    public static let code128Enable: UInt16 = 0xB501
    public static let code39Enable: UInt16 = 0xB601
    public static let code39FullAscii: UInt16 = 0xB602
    public static let code39TransmitStartStop: UInt16 = 0xB603
    public static let code39ChecksumMode: UInt16 = 0xB604
    public static let code93Enable: UInt16 = 0xB701
    public static let codabarEnable: UInt16 = 0xBA01
    public static let msiPlesseyEnable: UInt16 = 0xBC01
    public static let msiPlesseyChecksumMode: UInt16 = 0xBC02
    public static let interleaved2of5Enable: UInt16 = 0xBD01
    public static let gs1DataBar14Enable: UInt16 = 0xD201
    public static let gs1DataBarExpandedEnable: UInt16 = 0xD301
    public static let gs1DataBarLimitedEnable: UInt16 = 0xD401
    public static let pdf417Enable: UInt16 = 0xD801
    public static let microPdf417Enable: UInt16 = 0xD901
    public static let dataMatrixEnable: UInt16 = 0xDA01
    public static let rectangularDataMatrixEnable: UInt16 = 0xDA03
    public static let qrCodeEnable: UInt16 = 0xDB01
    public static let microQrEnable: UInt16 = 0xDC01
    public static let aztecEnable: UInt16 = 0xDD01
    public static let maxiCodeEnable: UInt16 = 0xDE01
    public static let fixedResponseFrame: UInt16 = 0x0000
    public static let decodeDataPacketHeader: UInt16 = 0x0000
}
