import Foundation

// Generated by tools/dev/generate_nt280h_parameter_constants.py
// Source: core/src/protocol/module/nt280h_parameter_catalog.inc
public enum Nt280hParameterCatalog {
    public static var all: [Nt280hParameterDefinition] {
        RuntimeParameterCatalogFallback.nt280hDefinitions
    }

    public static func findByID(_ parameterID: UInt16) -> Nt280hParameterDefinition? {
        all.first { $0.parameterID == parameterID }
    }
}
