import Foundation

// Generated by tools/dev/generate_se4750_parameter_constants.py
// Source: core/src/protocol/module/se4750_parameter_catalog.inc
public enum Se4750ParameterCatalog {
    public static var all: [Se4750ParameterDefinition] {
        RuntimeParameterCatalogFallback.se4750Definitions
    }

    public static func findByID(_ parameterID: UInt32) -> Se4750ParameterDefinition? {
        all.first { $0.parameterID == parameterID }
    }
}
